### ISSUE TITLE
Formalizing Personal Rights - new Ulex module? 

### ISSUE THREAD

**Issue by Arbitrage0** [proftomwbell/Ulex#10]
This might be getting into contentious territory, but given that the aim of Ulex is to "protect personal ... rights" [especially when considering that it could be used by entirely new societies/collectives - whether online or offline], wouldn't it make sense to add a separate module for human rights generally (similar to the optional Criminal module)? 

Not to give the impression that one could pick and choose rights in a sense, but we could create a basic and generally applicable set of rights which could have further add-ons to them depending on the society in question. To illustrate, the right to privacy would be universally applicable and "basic", whereas specific data protection rights when dealing with online intermediaries could act as an add-on and fleshed out in greater detail.

Thoughts?

**Comment by proftomwbell** [comment]
A triable idea, but as yet there is not a very good candidate for a universally accepted statement of such rights.  The UN Declaration of Human Rights, which one might hope would serve, will not, because it includes self-contradicting calls for welfare rights.
