### ISSUE TITLE
Divide new v. 1.1 into separate files

### ISSUE THREAD

**Issue by proftomwbell** [proftomwbell/Ulex#11]
Per @macterra the new version 1.1 (see [pull request #9](https://github.com/proftomwbell/Ulex/pull/9)) has in it CHANGELOG.md and stuff that would normally be kept in LICENSE.  It might thus be best to break those out in separate files.

**Comment by proftomwbell** [comment]
@macterra:  by all means, good sir, have at it!

**Comment by macterra** [comment]
I don't have permission to assign the issue to myself so please feel free to assign me. (Just a formality, I'll get started.)

**Comment by proftomwbell** [comment]
Harumph.  Can't see yet how to assign this to you.  I was able to assign you the "Links Broken" issue, and did so, and then reversed the assignment thinking it was perhaps preventing the assignment you request on *this* issue.  But, no; you simply do not appear among the possible assignees, here.  Only I do.
