### ISSUE TITLE
Links broken in footnotes

### ISSUE THREAD

**Issue by macterra** [proftomwbell/Ulex#12]
Several of the links in the footnotes in v1.1 are broken (e.g. https://github.com/proftomwbell/Ulex/tree/master/versions/1.1#fn43). 

Mea culpa, I will fix.

**Comment by proftomwbell** [comment]
You wanted to be assigned this, right?

**Comment by macterra** [comment]
@proftomwbell yes please assign me

**Comment by proftomwbell** [comment]
Trying, but get "Nothing to assign," as if you're not logged in as a potential assignee.

**Comment by proftomwbell** [comment]
Eureka!  Thanks for the pro-tip.
