### ISSUE TITLE
Citation should be:  Uniform Probate Code (2010)

### ISSUE THREAD

**Issue by proftomwbell** [proftomwbell/Ulex#13]
Both version 1.0 and 1.1 have a typo.  Both refer in rule 2.6.5. to "ULC, Uniform Probate Code (2014)", a provision that should in fact read, "ULC, Uniform Probate Code (2010)".  No 2014 version of the Code exists.

**Comment by Arbitrage0** [comment]
Made the edits, awaiting merge.

**Comment by proftomwbell** [comment]
I'm going to assume that it would not be necessary to use a new version number--1.1a, say--to trace so fine an edit.
