### ISSUE TITLE
Integrate hyperlink footnotes into main text

### ISSUE THREAD

**Issue by macterra** [proftomwbell/Ulex#17]
If a footnote is nothing but a link to an online legal document (i.e. most of the footnotes), there's no reason why the hyperlink can't be integrated directly into the text of Ulex.

**Comment by proftomwbell** [comment]
Agreed.  It was set up like that originally because the format didn't permit hyperlinks.

**Comment by macterra** [comment]
If #18 is approved it may be less work to do that one first. Just fyi.
