### ISSUE TITLE
Move repo to organization

### ISSUE THREAD

**Issue by macterra** [proftomwbell/Ulex#26]
Apparently admin responsibilities cannot be shared on personal repos. I recommend creating a [new github organization](https://github.com/organizations/new) (could also be named "Ulex") and moving this repo there.

**Comment by macterra** [comment]
Just fyi this [joker](https://github.com/ulex) stole our name so we won't be able to name the new organization "Ulex".

**Comment by proftomwbell** [comment]
D'oh.  There are some other uses of "ulex" out there, too--one distinctly code-related.  Open to suggestions for better arrangements....  Hopefully the present one does not cast too large a cloud on the project.
