### ISSUE TITLE
Version nixing governmental immunity

### ISSUE THREAD

**Issue by proftomwbell** [proftomwbell/Ulex#30]
The current version of Ulex invokes ALI, Restatement of Torts, Second (1965-79).  That rule set includes §§ 895 A-D, providing for forms of governmental immunity.  There are good reasons to doubt that those belong in the common law, as documented in "Your Next Government?".  But the rules do reflect the weight of US authority.  From bogus roots, the doctrine has worked its way throughout US law.

Perhaps it would be appropriate to offer a version of Ulex without those sections.  It would probably not be appropriate to add those to the default, main version.

**Comment by macterra** [comment]
Definitely interested in a version without govt immunity

**Comment by proftomwbell** [comment]
I've now started a pull request for the edit, proposing it as part of a package of edits for Ulex v. 1.2.
