### ISSUE TITLE
Is there a plan to eventually have open source restatements in digital form?

### ISSUE THREAD

**Issue by stalcottsmith** [proftomwbell/Ulex#46]
Ulex 1.2 references printed books.  Since I am not a lawyer, it seems strange to me that the law is not entirely digital, easily indexed, and more or less freely accessible except that perhaps until now it has been in nobody's particular interest to make it so.  What is involved in such a project?

**Comment by proftomwbell** [comment]
See "Your Next Government?" chapter 3.7 for an explanation of the copyright status of the substantive rules incorporated into Ulex.  Basically:  You are right; the American Law Institute is to blame; it is wrong.
